#!/bin/bash
echo "Installing dependencies"
sudo apt-get install python-software-properties
sudo apt-get update
echo "Installing nodejs, npm and mongodb"
sudo apt-get install nodejs npm mongodb

sudo npm install -g nodemon
npm install
